name: stage-lidar
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - geopandas
  - rasterio
  - shapely
  - pyproj
  - pyogrio
  - scipy
  - numba
  - matplotlib
  - requests
  - pvlib
